[auth.email.template.invite]
subject = "You are invited to SixFigJob.com. Let's find your next $100k+ Job!"
content_path = "/etc/supabase/templates/invite.html"

[auth.email.template.confirmation]
subject = "Confirm your signup | SixFigJob.com"
content_path = "/etc/supabase/templates/confirm.html"

[auth.email.template.recovery]
subject = "Reset your password | SixFigJob.com"
content_path = "/etc/supabase/templates/recovery.html"

[auth.email.template.magic_link]
subject = "Your magic link | SixFibJob.com"
content_path = "/etc/supabase/templates/magic_link.html"

[auth.email.template.email_change]
subject = "Confirm email change | SixFigJob.com (Config)"
content_path = "/etc/supabase/templates/email_change.html"